
CREATE TABLE IF NOT EXISTS EventFlow(
	GlobalSequenceNumber bigint  GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	BatchId uuid NOT NULL,
	AggregateName varchar(255) NOT NULL,
	AggregateId varchar(255) NOT NULL,
	AggregateSequenceNumber int NOT NULL,
	Data Text NOT NULL,
	Metadata Text NOT NULL,
	CONSTRAINT "PK_EventFlow" PRIMARY KEY
	(
		GlobalSequenceNumber
	)
);


CREATE UNIQUE INDEX IF NOT EXISTS "IX_EventFlow_AggregateName_AggregateId_AggregateSequenceNumber" ON EventFlow
(
	AggregateName,
	AggregateId,
	AggregateSequenceNumber
);

