<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;netcoreapp3.1;net6.0;net8.0</TargetFrameworks>
    <Title>EventFlow.Elasticsearch</Title>
    <Description>Elasticsearch support for EventFlow</Description>
    <PackageTags>CQRS ES event sourcing Elasticsearch</PackageTags>
    <PackageReleaseNotes>UPDATED BY BUILD</PackageReleaseNotes>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0" PrivateAssets="All" />
    <PackageReference Include="NEST" Version="7.8.2" />
    <PackageReference Include="newtonsoft.json" Version="13.0.1" />    
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EventFlow\EventFlow.csproj" />
  </ItemGroup>
</Project>
