<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net6.0;net7.0;net8.0;net9.0</TargetFrameworks>
		<PackageId>ClearFlow.Newtonsoft</PackageId>		
		<Title>ClearFlow.Newtonsoft</Title>
		<Authors>Jan Feyen, Warren Pieterse, Kyle Bradley</Authors>
		<Owners>Rasmus Mikkelsen</Owners>
		<Company>Rasmus Mikkelsen</Company>
		<Copyright>Copyright (c) Rasmus Mikkelsen 2015 - 2021</Copyright>
		<Description>NewtonsoftJson Serializer for EventFlow</Description>
		<PackageTags>CQRS ES event sourcing Newtonsoft</PackageTags>		
		<PackageReleaseNotes>UPDATED BY BUILD</PackageReleaseNotes>
		<IsPackable>true</IsPackable>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="System.Text.Json" Version="9.0.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\EventFlow\EventFlow.csproj" />
	</ItemGroup>

</Project>