<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net6.0;net7.0;net8.0;</TargetFrameworks>
	<PackageId>ClearFlow.Sql</PackageId>
	<Title>ClearFlow.Sql</Title>
    <Authors>Kyle Bradley, Rasmus Mikkelsen</Authors>
    <Company>Kyle Bradley, Rasmus Mikkelsen</Company>
    <Copyright>Copyright (c) Rasmus Mikkelsen 2015 - 2021</Copyright>
    <Description>Generic SQL support for EventFlow</Description>
    <PackageTags>CQRS ES event sourcing SQL</PackageTags>
    <PackageReleaseNotes>UPDATED BY BUILD</PackageReleaseNotes>
	<Version>0.2.2</Version>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.35" />
    <PackageReference Include="dbup-core" Version="6.0.3" />
	<PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
	<PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EventFlow\EventFlow.csproj" />
  </ItemGroup>
</Project>
