<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net6.0;net7.0;net8.0</TargetFrameworks>
	<PackageId>ClearFlow.PostgreSql</PackageId>
    <Title>ClearFlow.PostgreSql</Title>
    <Authors>Kyle Bradley, Rida Messaoudene</Authors>
    <Company>Kyle Bradley</Company>
    <Copyright>Copyright (c) Rasmus Mikkelsen 2015 - 2021</Copyright>
    <Description>POSTGRESQL support for EventFlow</Description>
    <PackageTags>CQRS ES event sourcing POSTGRESQL</PackageTags>
    <NeutralLanguage>en-US</NeutralLanguage>
    <PackageReleaseNotes>UPDATED BY BUILD</PackageReleaseNotes>
	<Version>0.1.5</Version>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="EventStores\Scripts\0001 - Create table EventFlow.sql" />
    <None Remove="EventStores\Scripts\0002 - Create eventdatamodel_list_type.sql" />
    <None Remove="SnapshotStores\Scripts\0001 - Create EventFlowSnapshots.sql" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="EventStores\Scripts\0001 - Create table EventFlow.sql" />
    <EmbeddedResource Include="EventStores\Scripts\0002 - Create eventdatamodel_list_type.sql" />
    <EmbeddedResource Include="SnapshotStores\Scripts\0001 - Create EventFlowSnapshots.sql" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="dbup-postgresql" Version="5.0.40" />
	 <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
  </ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
		<PackageReference Include="Npgsql" Version="8.0.4" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net7.0' Or '$(TargetFramework)' == 'net6.0'">
		<PackageReference Include="Npgsql" Version="7.0.8" />
	</ItemGroup>
	
  <ItemGroup>
    <ProjectReference Include="..\EventFlow.Sql\EventFlow.Sql.csproj" />
    <ProjectReference Include="..\EventFlow\EventFlow.csproj" />
  </ItemGroup>

</Project>
