<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	  <TargetFrameworks>net6.0;net7.0;net8.0;net9.0</TargetFrameworks>
	  <PackageId>ClearFlow.MongoDB</PackageId>
	  <Title>ClearFlow.MongoDB</Title>
	  <Authors>Kyle Bradley, Jan Feyen, Warren Pieterse</Authors>
	  <Description>MongoDB ReadStore and Snapshot Persistence for EventFlow</Description>
	  <PackageTags>CQRS ES event sourcing MongoDB</PackageTags>
	  <PackageReleaseNotes>UPDATED BY BUILD</PackageReleaseNotes>
	  <Version>0.2.4</Version>
	  <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
    <PackageReference Include="MongoDB.Driver" Version="3.2.1" />
    <PackageReference Include="System.Text.Json" Version="9.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EventFlow\EventFlow.csproj" />
  </ItemGroup>
  
</Project>