<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net6.0;net7.0;net8.0</TargetFrameworks>
	<PackageId>ClearFlow</PackageId>
	<Title>ClearFlow</Title>
    <Description>Forked project based on EventFlow:
Async/await first CQRS+ES and DDD framework for .NET - https://docs.geteventflow.net/</Description>
    <PackageTags>CQRS ES event sourcing</PackageTags>
    <PackageReleaseNotes>Updated to include latest EventFlow changes.&amp; .net 8.0</PackageReleaseNotes>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\EventFlow.xml</DocumentationFile>
    <IsPackable>true</IsPackable>
    <Version>0.1.5</Version>
    <Authors>Kyle Bradley, Rasmus Mikkelsen</Authors>
    <Company>Kyle Bradley</Company>
    <Product>ClearFlow</Product>
    <RepositoryUrl>https://github.com/kyle-bradley/EventFlow</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
    <PackageReference Include="System.Linq.Async" Version="6.0.1" />
	  <PackageReference Include="JetBrains.Annotations" Version="2024.2.0">
		  <PrivateAssets>All</PrivateAssets>
	  </PackageReference>
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netcoreapp3.1'">
	  <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="3.1.10" />
	  <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="3.1.10" />
	  <PackageReference Include="Microsoft.Extensions.Logging" Version="3.1.10" />
	  <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="3.1.10" />
	  <PackageReference Include="System.Text.Json" Version="6.0.9" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net6.0'">
	  <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="6.0.2" />
	  <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="6.0.1" />
	  <PackageReference Include="Microsoft.Extensions.Logging" Version="6.0.0" />
	  <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="6.0.0" />
	  <PackageReference Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net7.0'">
	  <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="7.0.0" />
	  <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="7.0.0" />
	  <PackageReference Include="Microsoft.Extensions.Logging" Version="7.0.0" />
	  <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="7.0.0" />
	  <PackageReference Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
	  <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="8.0.1" />
	  <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
	  <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.1" />
	  <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="8.0.1" />
	  <PackageReference Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>
</Project>