# Original file from https://github.com/kiazhi/Windows-Containers

# MIT License
# 
# Copyright (c) 2018 Kia Zhi Tang
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

ARG WINDOWS_VERSION='ltsc2022'  

FROM mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2022

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

ARG POSTGRESQL_VERSION=9.6.9

RUN \
    if(!(Test-Path -Path 'C:\Temp')) \
    { \
        New-Item \
            -Path 'C:\Temp' \
            -ItemType Directory \
            -Verbose | Out-Null ; \
    } ; \
    \
    Invoke-WebRequest \
        -Uri "https://get.enterprisedb.com/postgresql/postgresql-$ENV:POSTGRESQL_VERSION-1-windows-x64-binaries.zip" \
        -OutFile "C:\Temp\postgresql-$ENV:POSTGRESQL_VERSION-1-windows-x64-binaries.zip" \
        -UseBasicParsing \ 
        -Verbose ; \
    \
    Expand-Archive \
        -Path "C:\Temp\postgresql-$ENV:POSTGRESQL_VERSION-1-windows-x64-binaries.zip" \
        -DestinationPath 'C:\\Program Files' \
        -Verbose ; \
    \
    New-Item \
        -Path $('C:\Program Files\pgsql\data') \
        -ItemType Directory \
        -Verbose | Out-Null ; \
    \
    Set-ItemProperty \
        -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Environment' \
        -Name 'Path' \
        -Value $($ENV:Path + ';C:\Program Files\pgsql\bin') \
        -Verbose ;

RUN \
    postgres --version \
    pg_ctl -D 'C:\Program Files\pgsql\data' initdb \
    regsvr32 'C:\Program Files\pgsql\lib\pgevent.dll' \
    pg_ctl register -N 'PostgreSQL' -D 'C:\Program Files\pgsql\data' -l logfile \
    Start-Service -Name PostgreSQL -Verbose \
    pg_ctl status -D 'C:\Program Files\pgsql\data' \
    Remove-Item -Path 'C:\\Temp' -Recurse -Verbose

EXPOSE 5432
