<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;netcoreapp3.1;net6.0;net8.0</TargetFrameworks>
    <Title>EventFlow.SQLite</Title>
    <Description>SQLite event store for EventFlow</Description>
    <PackageTags>CQRS ES event sourcing SQLite</PackageTags>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\EventFlow.SQLite.xml</DocumentationFile>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0" PrivateAssets="All" />
    <PackageReference Include="System.Data.SQLite.Core" Version="1.0.119" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <PackageReference Include="dbup-sqlserver" Version="[6.0.0,)" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net6.0'">
    <PackageReference Include="dbup-sqlserver" Version="5.0.40" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netcoreapp3.1'">
    <PackageReference Include="dbup-sqlserver" Version="5.0.40" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.1'">
    <PackageReference Include="dbup-sqlserver" Version="5.0.40" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EventFlow.Sql\EventFlow.Sql.csproj" />
  </ItemGroup>
</Project>