<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net6.0;net7.0;net8.0;net9.0</TargetFrameworks>
    <IsPackable>False</IsPackable>
	  <WarningsNotAsErrors>NU1901;NU1902;NU1903;NU1904</WarningsNotAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="NUnit" Version="4.2.2" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
  </ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net9.0'">
		<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.0" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.2" />
		<PackageReference Include="Npgsql" Version="9.0.2" />
	</ItemGroup>


	<ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
		<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="8.0.11" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.11" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.11" />
		<PackageReference Include="Npgsql" Version="8.0.6" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net7.0' Or '$(TargetFramework)' == 'net6.0'">
		<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="7.0.20" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="7.0.20" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.20" />
		<PackageReference Include="Npgsql" Version="9.0.2" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="7.0.18" />
	</ItemGroup>
	
	<ItemGroup>
		<ProjectReference Include="..\EventFlow.EntityFramework\EventFlow.EntityFramework.csproj" />
		<ProjectReference Include="..\EventFlow.PostgreSql.Tests\EventFlow.PostgreSql.Tests.csproj" />
		<ProjectReference Include="..\EventFlow.TestHelpers\EventFlow.TestHelpers.csproj" />
		<ProjectReference Include="..\EventFlow\EventFlow.csproj" />
	</ItemGroup>

</Project>
