//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyCompany("Rasmus Mikkelsen")]
[assembly: AssemblyProduct("EventFlow")]
[assembly: AssemblyVersion("0.0.1")]
[assembly: AssemblyFileVersion("0.0.1")]
[assembly: AssemblyInformationalVersion("0.0.1")]
[assembly: AssemblyCopyright("Copyright (c) Rasmus Mikkelsen 2015 - 2017 (SHA:developer build)")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyConfiguration("Release")]
[assembly: ComVisible(false)]

