// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("0.0.1")]
[assembly: AssemblyInformationalVersionAttribute("0.0.1")]
[assembly: AssemblyFileVersionAttribute("0.0.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.0.1";
    }
}
