//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyDescription("developer build")]
[assembly: AssemblyVersion("0.33.2172")]
[assembly: AssemblyFileVersion("0.33.2172")]
[assembly: AssemblyInformationalVersion("0.33.2172")]
[assembly: AssemblyCopyright("Copyright (c) Rasmus Mikkelsen 2015 - 2016")]

