name: Release

on:
  push:
    branches:
    - release-v1

jobs:
  build:
    uses: ./.github/workflows/pipeline.yml
    with:
      bake-convention: Release
      bake-destination: "nuget>github,nuget,release>github"
