name: Test report

on:
  workflow_run:
    workflows:
    - 'Release'
    - 'Pull-request'
    types:
    - completed

jobs:
  report:
    runs-on:
    - ubuntu-22.04

    permissions:
      id-token: write
      contents: read
      checks: write

    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: test-results
        name: Test results
        path: '**/*.trx'
        reporter: dotnet-trx
